module.exports = {
  apps: [
    {
      name: 'pion-whip-publisher',
      cwd: __dirname,
      script: './run_pion_whip.sh',
      interpreter: '/bin/bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 20,
      env: {
        WHIP_URL: 'http://103.124.94.194:8889/cam1/whip',
        DEVICE: '/dev/video0',
        WIDTH: '1280',
        HEIGHT: '720',
        FPS: '15',
        VIDEO_PIPELINE: 'auto',
        IMAGE_ENHANCE: '1',
        BITRATE_KBPS: '3000',
        X264_SPEED_PRESET: 'ultrafast',
        H264_I_FRAME_PERIOD: '30',
        PRESET_CAMERA: '1',
        AUTO_EXPOSURE: '3',
        GAIN: '0',
        FIRST_RTP_TIMEOUT: '12s',
        PION_RUN_MODE: 'binary',
        GO_MOD_DOWNLOAD: '0',
        BRIGHTNESS: '0.14',
        CONTRAST: '1.22',
        SATURATION: '1.18',
        HUE: '0.03',
        GAMMA: '0.90',
        SHARPNESS: '8',
        SHARPEN: '0.65',
        SHARPEN_SIGMA: '0.5',
        RTP_LISTEN_ADDR: '127.0.0.1:5004',
        LOG_RTP: '0',
      },
    },
  ],
};
